import { describe, expect, it } from 'vitest';
import {
  REQUIRED_ATTRIBUTION_LINE,
  validatePrAttribution,
} from '../../scripts/validate-pr-attribution.mjs';

const CLAUDE_CODE_FOOTER = '🤖 Generated with [Claude Code](https://claude.com/claude-code)';

describe('validatePrAttribution', () => {
  it('passes when the body contains exactly the repository-standard attribution line', () => {
    const body = `## Summary\n\nDid the thing.\n\n${REQUIRED_ATTRIBUTION_LINE}\n`;
    expect(validatePrAttribution(body)).toEqual({ valid: true, errors: [] });
  });

  it('fails on the stock Claude Code provider-default footer (regression: PR #10, PR #13)', () => {
    const body = `## Summary\n\nDid the thing.\n\n${CLAUDE_CODE_FOOTER}\n`;
    const result = validatePrAttribution(body);
    expect(result.valid).toBe(false);
    expect(result.errors.join('\n')).toContain('Missing required attribution line');
    expect(result.errors.join('\n')).toContain('Provider-default attribution');
  });

  it('fails when both the repository-standard line and the provider-default footer are present', () => {
    const body = `## Summary\n\n${REQUIRED_ATTRIBUTION_LINE}\n\n${CLAUDE_CODE_FOOTER}\n`;
    const result = validatePrAttribution(body);
    expect(result.valid).toBe(false);
    expect(result.errors.join('\n')).toContain('Provider-default attribution');
  });

  it('fails when neither attribution line is present', () => {
    const body = '## Summary\n\nDid the thing.\n';
    const result = validatePrAttribution(body);
    expect(result.valid).toBe(false);
    expect(result.errors).toEqual([`Missing required attribution line: "${REQUIRED_ATTRIBUTION_LINE}"`]);
  });

  it('fails when the repository-standard line appears more than once', () => {
    const body = `${REQUIRED_ATTRIBUTION_LINE}\n\nBody text.\n\n${REQUIRED_ATTRIBUTION_LINE}\n`;
    const result = validatePrAttribution(body);
    expect(result.valid).toBe(false);
    expect(result.errors).toEqual([
      'Required attribution line must appear exactly once, found 2 occurrences.',
    ]);
  });

  it('fails on a near-match/malformed attribution line rather than silently passing', () => {
    const body = 'Generated by Claude and Mike.\n';
    const result = validatePrAttribution(body);
    expect(result.valid).toBe(false);
    expect(result.errors).toEqual([`Missing required attribution line: "${REQUIRED_ATTRIBUTION_LINE}"`]);
  });

  it('treats an empty or missing body as failing', () => {
    expect(validatePrAttribution('').valid).toBe(false);
    expect(validatePrAttribution(undefined).valid).toBe(false);
    expect(validatePrAttribution(null).valid).toBe(false);
  });
});
